-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 00:59:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema immunihealth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema immunihealth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `immunihealth` DEFAULT CHARACTER SET utf8 ;
USE `immunihealth` ;

-- -----------------------------------------------------
-- Table `immunihealth`.`Pasien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immunihealth`.`Pasien` (
  `pasien_id` INT(10) NOT NULL AUTO_INCREMENT,
  `nama_pasien` VARCHAR(45) NULL,
  `tanggal_lahir` DATE NULL,
  `jenis_kelamin` VARCHAR(45) NULL,
  PRIMARY KEY (`pasien_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immunihealth`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immunihealth`.`User` (
  `user_id` VARCHAR(10) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `nama_user` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `no_telp` INT(10) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immunihealth`.`Layanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immunihealth`.`Layanan` (
  `pasien_id` INT(10) NOT NULL AUTO_INCREMENT,
  `grup` VARCHAR(45) NULL,
  `jenis_layanan` VARCHAR(20) NULL,
  PRIMARY KEY (`layanan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immunihealth`.`Dokter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immunihealth`.`Dokter` (
  `dokter_id` VARCHAR(10) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `nama_dokter` VARCHAR(45) NULL,
  PRIMARY KEY (`dokter_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immunihealth`.`Jadwal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immunihealth`.`Jadwal` (
  `jadwal_id` INT(10) NOT NULL AUTO_INCREMENT,
  `hari` VARCHAR(10) NULL,
  `waktu_mulai` TIME NULL,
  `waktu_selesai` TIME NULL,
  `dokter_id` VARCHAR(10) NULL,
  PRIMARY KEY (`jadwal_id`),
  INDEX `fk_Jadwal_Dokter1_idx` (`dokter_id` ASC),
  CONSTRAINT `fk_Jadwal_Dokter1`
    FOREIGN KEY (`dokter_id`)
    REFERENCES `immunihealth`.`Dokter` (`dokter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `immunihealth`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immunihealth`.`Appointment` (
  `appointment_id` INT(10) NOT NULL AUTO_INCREMENT,
  `tgl_waktu_permintaan` DATETIME NULL,
  `nama_wali` VARCHAR(45) NULL,
  `nama_pasien` VARCHAR(45) NULL,
  `tanggal_lahir` DATE NULL,
  `jenis_kelamin` VARCHAR(45) NULL,
  `notes` VARCHAR(45) NULL,
  `user_id` VARCHAR(10) NOT NULL,
  `layanan_id` INT(10) NOT NULL,
  `dokter_id` VARCHAR(10) NULL,
  `jadwal_id` INT(10) NULL,
  `is_acc` SMALLINT NULL,
  `is_done` SMALLINT NULL,
  `is_denied` SMALLINT NULL,
  PRIMARY KEY (`appointment_id`),
  INDEX `fk_Appointment_User1_idx` (`user_id` ASC),
  INDEX `fk_Appointment_Layanan1_idx` (`layanan_id` ASC),
  INDEX `fk_Appointment_Dokter1_idx` (`dokter_id` ASC),
  CONSTRAINT `fk_Appointment_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `immunihealth`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Layanan1`
    FOREIGN KEY (`layanan_id`)
    REFERENCES `immunihealth`.`Layanan` (`layanan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Dokter1`
    FOREIGN KEY (`dokter_id`)
    REFERENCES `immunihealth`.`Dokter` (`dokter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immunihealth`.`Petugas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immunihealth`.`Petugas` (
  `petugas_id` VARCHAR(10) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `nama_petugas` VARCHAR(45) NULL,
  PRIMARY KEY (`petugas_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
